// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6htEXhLbMNSdtOCdilo5I0T5A3jDQ9_E',
    appId: '1:509186990141:android:8b3f968bbe76cb7be6ca54',
    messagingSenderId: '509186990141',
    projectId: 'chat-app-test-c9013',
    databaseURL: 'https://chat-app-test-c9013-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-test-c9013.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDAdF20kDk5onyaI7ae6XX4IpxQxwflA0',
    appId: '1:509186990141:ios:8d1ea5ee3d98f353e6ca54',
    messagingSenderId: '509186990141',
    projectId: 'chat-app-test-c9013',
    databaseURL: 'https://chat-app-test-c9013-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-test-c9013.firebasestorage.app',
    iosBundleId: 'com.example.chatty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ-VNif8GCcpf6TtGV_TCLKt1aVISZgoE',
    appId: '1:509186990141:web:dfa62b2077338587e6ca54',
    messagingSenderId: '509186990141',
    projectId: 'chat-app-test-c9013',
    authDomain: 'chat-app-test-c9013.firebaseapp.com',
    databaseURL: 'https://chat-app-test-c9013-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-test-c9013.firebasestorage.app',
    measurementId: 'G-7CW685PFS2',
  );
}
